### PR TITLE
Make adjustments necessary for use within Atom's new release publisher application

### PR DESCRIPTION
**Pull request by nathansobo**
- Improve commit fetching from the GitHub API to work around 250 commit limitation.
- Fetch everything in parallel to improve latency. Add context to log messages to make things somewhat less confusing now that they're all mixed up.
- Allow GitHub access token to be assigned programmatically. We use the token of the authenticated user so environment variables don't work.

/cc @as-cii

### CODE REVIEW

**Comment by benogle** [comment]
👍  Smaller diff than I was expecting

**Comment by benogle** [comment]
Also readme update for the new function?

**Comment by nathansobo** [comment]
Yeah I can hit the README. Jumped back to our web app to make some more adjustments based on what I learned doing this and will circle back.

**Comment by benogle** [comment]
@nathansobo You guys still using this?

**Comment by nathansobo** [comment]
I think @iolsen has been working on constructing release notes as an automated part of our deployment process, but I'm not sure how he's implementing it. Presumably he's not using this PR.

**Comment by iolsen** [comment]
Yeah I wasn't even aware of this PR, but I've been starting from scratch. I'm not very far along yet. I might refer to this at some point but otherwise I don't think we care if it gets merged.

**Comment by daviwil** [comment]
Looping back around to this again, trying to get `pr-changelog` hooked up into the release publisher :)  What else needs to be done to get this merged/released?  Thanks!

**Comment by benogle** [comment]
Is that comment for @nathansobo? I'm happy with whatever, this PR seems fine. Also if easier we can move this to the atom org...

**Comment by daviwil** [comment]
Sorry, should have been more clear!  I was mainly asking for your opinion since it seemed from the comments that Nathan was done.  If you'd like to transfer this repo over to the Atom org, I'd be happy to help get that done.  According to [this documentation](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-to-an-organization) you should just be able to transfer over the GitHub repo to the Atom org (looks like you have repo creation perms) then I should be able to republish it to npm under the `@atom` org.

Thanks a lot!

**Comment by benogle** [comment]
I tried, and it said I dont have atom org repo creation permissions. If you add repo creation to my account, i can add it. Or I can transfer it to you or nathan, then yall can move it into the org. Let me know what you want to do

**Comment by daviwil** [comment]
Sorry about that!  Flipped a switch, try it again.

**Comment by benogle** [comment]
Ok, done. Feel free to take it away before I do anything sketchy! :p

**Comment by daviwil** [comment]
Yep, it worked, thanks a lot!  Is it possible you could add me as an owner on the npm package too?  Maybe it's better to keep using the same package name rather than moving it, not sure who else depends on this package.

**Comment by benogle** [comment]
Ok, you are now an owner on the npm package

**Comment by daviwil** [comment]
Thanks a lot Ben!

**Pull request merged**
